Rgfbealf7 23 glibcv2.17
xenit-eu/scw-2fa-init pull request #2
Opened 2023-08-23 09:12 UTC by codingBenVdS

ticket: https://xenitsupport.jira.com/browse/RGFBEALF7-23

2023-08-24 08:15 UTC, WimCrols commented
The build fails. Seems like you need a tag.

2023-08-24 08:16 UTC, WimCrols requested changes

2023-08-24 08:16 UTC, WimCrols commented on README.md
> +To run this project you have to download the binary from the Github Actions page from a release.
This is not correct: a release has nothing to do with Github Actions. You can have a release without there being any GHA build.

2023-08-24 08:18 UTC, WimCrols commented on .github/workflows/release.yml
> +  pull_request:
This yml was never meant to be run on a pull request, but only on a tag action. This is the reason why it fails for this PR. I think you need to revert this OR add separate yml for build & test (if you think it's useful).

2023-08-25 07:13 UTC, codingBenVdS commented on README.md
> +To run this project you have to download the binary from the Github Actions page from a release.
But you have to browse to: https://github.com/xenit-eu/scw-2fa-init/actions in order tofind the link to the binary

2023-08-25 07:14 UTC, codingBenVdS commented on .github/workflows/release.yml
> +  pull_request:
I will revert this to the original way. I added p_r for testing purposes

2023-08-28 07:56 UTC, WimCrols commented on README.md
> +To run this project you have to download the binary from the Github Actions page from a release.
No, you have to go to https://github.com/xenit-eu/scw-2fa-init/releases . Github actions just has a log line that points to it, because it creates a release. But a human can do that too.

2023-08-28 12:48 UTC, codingBenVdS commented on README.md
> +To run this project you have to download the binary from the Github Actions page from a release.
Changes made to README.

2023-08-28 13:23 UTC, merged